function branchOut = gmos_merge_fixT_mu_branch_segments(branchOld, branchNew, k1)
%GMOS_MERGE_FIXT_MU_BRANCH_SEGMENTS
% Keep branchOld up to k1, then append branchNew from entry 2 onward.

    branchOut = struct();

    branchOut.y = [ ...
        branchOld.y(1:k1); ...
        branchNew.y(2:end)];

    branchOut.z = [ ...
        branchOld.z(1:k1); ...
        branchNew.z(2:end)];

    branchOut.mu = [ ...
        branchOld.mu(1:k1); ...
        branchNew.mu(2:end)];

    branchOut.T = [ ...
        branchOld.T(1:k1); ...
        branchNew.T(2:end)];

    branchOut.rho = [ ...
        branchOld.rho(1:k1); ...
        branchNew.rho(2:end)];

    branchOut.info = [ ...
        branchOld.info(1:k1); ...
        branchNew.info(2:end)];

    branchOut.success = [ ...
        branchOld.success(1:k1); ...
        branchNew.success(2:end)];

    branchOut.dsUsed = [ ...
        branchOld.dsUsed(1:k1); ...
        branchNew.dsUsed(2:end)];

    branchOut.EGMOS = [ ...
        branchOld.EGMOS(1:k1); ...
        branchNew.EGMOS(2:end)];

    if isfield(branchNew, 'scale')
        branchOut.scale = branchNew.scale;
    elseif isfield(branchOld, 'scale')
        branchOut.scale = branchOld.scale;
    end
end